defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] %>
  username: postgres
  password:

development:
  database: verb_development
  <<: *defaults

test:
  database: verb_test
  min_messages: WARNING
  <<: *defaults

production:
  database: verb_production
  <<: *defaults
