defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: verb_development
  <<: *defaults

test:
  database: verb_test
  min_messages: WARNING
  <<: *defaults

production:
  database: verb_production
  <<: *defaults
