defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>
  username: postgres
  password: 

development:
  database: verb_development
  <<: *defaults

test:
  database: verb_test
  min_messages: WARNING
  <<: *defaults

production:
  database: verb_production
  <<: *defaults
